---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run commands over kops master  
      command: "cd /opt"
      command: "rm -rf CICD-Git-jenkins-maven-tomcat"
      command: "git clone https://github.com/Raam043/CICD-Git-jenkins-maven-tomcat.git"
    
