---
- hosts: rnb
  become: True
  tasks:
  
    - name: Delete old folder
      command: "rm -rf /opt/*
      
    - name: Git clone
      command: "git clone https://github.com/Raam043/CICD-Git-jenkins-maven-tomcat.git /opt/"
            
    - name: Applying Manifest file  
      command: "kubectl apply -f /opt/deployment.yml"
      
    - name: Restarting service
      command: "kubectl rollout restart deployment"

    
