---
- hosts: rnb
  become: True
  tasks:
  
    - name: Delete old folder
      command: "rm -rf /root/git"
      
    - name: Crteate work Directory
      command: "mkdir /root/git"
      
    - name: Git clone
      command: "git clone https://github.com/Raam043/CICD-Git-jenkins-maven-tomcat.git /root/git"
            
    - name: Applying Manifest file  
      command: "kubectl apply -f /root/git/deployment.yml"
      
    - name: Restarting service
      command: "kubectl rollout restart deployment"

    
