---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      command: "docker stop tomcat & docker rm -f tomcat & docker image rm -f tomcat"
    
    - name: Run docker container
      docker_container:
        name: tomcat
        image: raam043/tomcat-project
        state: started
        exposed_ports:
        - "8080"
        ports:
        - "8080:8080"
 
